name: Sync Docker Images to Private Registry (Hierarchical Sync)
run-name: Image - ${{ inputs.source_image }}

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: "Source image (e.g. docker.io/golang:1.26.2-bookworm)"
        required: true
        default: "docker.io/golang:1.26.2-bookworm"

jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HIERARCHICAL_PRIVATE_REGISTRY }}
          username: ${{ secrets.HIERARCHICAL_DOCKER_USER }}
          password: ${{ secrets.HIERARCHICAL_DOCKER_TOKEN }}

      - name: 🚀 Sync Image using Skopeo
        run: |
          SRC="${{ github.event.inputs.source_image }}"
          DEST="${{ secrets.HIERARCHICAL_BASE_URL }}/${{ github.event.inputs.source_image }}"
          
          echo "Starting sync: $SRC -> $DEST"

          set +e
          docker run --rm \
            quay.io/skopeo/stable:latest \
            copy \
            --all \
            --src-tls-verify=true \
            --dest-tls-verify=true \
            --dest-creds "${{ secrets.HIERARCHICAL_DOCKER_USER }}:${{ secrets.HIERARCHICAL_DOCKER_TOKEN }}" \
            "docker://$SRC" \
            "docker://$DEST"
          ret=$?
          set -e

          if [ $ret -gt 0 ]; then

            echo "⚠️ skopeo failed, fallback to regctl..."

            docker run --rm \
              -v ~/.docker/config.json:/root/.docker/config.json:ro \
              regclient/regctl:latest \
              image copy \
              --format docker \
              "$SRC" \
              "$DEST"
          fi

      - name: ✅ Done
        run: |
          echo "Image synced successfully to Private Registry."
